// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ38jsAvAuAJ0sXdo14YZ_70jFAeMvnC0',
    appId: '1:697623816853:web:7b9d681a167ba1b0b2899c',
    messagingSenderId: '697623816853',
    projectId: 'duofinance',
    authDomain: 'duofinance.firebaseapp.com',
    storageBucket: 'duofinance.appspot.com',
    measurementId: 'G-FY7N3YSNBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgRovqy8dNuzqyUHGWTWggmrzwUzl7J3o',
    appId: '1:697623816853:android:a9c2ba11578cc737b2899c',
    messagingSenderId: '697623816853',
    projectId: 'duofinance',
    storageBucket: 'duofinance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_oNrN1w_8hxV0TybsbhRKqlSm13_owfs',
    appId: '1:697623816853:ios:3d09925bc33706b4b2899c',
    messagingSenderId: '697623816853',
    projectId: 'duofinance',
    storageBucket: 'duofinance.appspot.com',
    iosBundleId: 'com.example.duofinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_oNrN1w_8hxV0TybsbhRKqlSm13_owfs',
    appId: '1:697623816853:ios:3d09925bc33706b4b2899c',
    messagingSenderId: '697623816853',
    projectId: 'duofinance',
    storageBucket: 'duofinance.appspot.com',
    iosBundleId: 'com.example.duofinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ38jsAvAuAJ0sXdo14YZ_70jFAeMvnC0',
    appId: '1:697623816853:web:f43abb52a258d0cfb2899c',
    messagingSenderId: '697623816853',
    projectId: 'duofinance',
    authDomain: 'duofinance.firebaseapp.com',
    storageBucket: 'duofinance.appspot.com',
    measurementId: 'G-XWJT85HQQD',
  );
}
